// ---------------------------------------------------------------------------
// ../modules/wxbind/src/wxpropgrid_propgrid.cpp was generated by genwxbind.lua 
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------


#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

#ifndef WX_PRECOMP
     #include "wx/wx.h"
#endif

#include "wxlua/wxlstate.h"
#include "wxbind/include/wxpropgrid_bind.h"

#ifdef __GNUC__
    #pragma GCC diagnostic ignored "-Wunused-variable"
#endif // __GNUC__



// ---------------------------------------------------------------------------
// ../modules/wxbind/src/wxpropgrid_bind.cpp was generated by genwxbind.lua 
//
// Any changes made to this file will be lost when the file is regenerated.
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// wxLuaGetEventList_wxpropgrid() is called to register events
// ---------------------------------------------------------------------------

wxLuaBindEvent* wxLuaGetEventList_wxpropgrid(size_t &count)
{
    static wxLuaBindEvent eventList[] =
    {

        { 0, 0, 0 },
    };
    count = sizeof(eventList)/sizeof(wxLuaBindEvent) - 1;
    return eventList;
}

// ---------------------------------------------------------------------------
// wxLuaGetDefineList_wxpropgrid() is called to register #define and enum
// ---------------------------------------------------------------------------

wxLuaBindNumber* wxLuaGetDefineList_wxpropgrid(size_t &count)
{
    static wxLuaBindNumber numberList[] =
    {

        { 0, 0 },
    };
    count = sizeof(numberList)/sizeof(wxLuaBindNumber) - 1;
    return numberList;
}

// ---------------------------------------------------------------------------

// wxLuaGetStringList_wxpropgrid() is called to register #define_string
// ---------------------------------------------------------------------------

wxLuaBindString* wxLuaGetStringList_wxpropgrid(size_t &count)
{
    static wxLuaBindString stringList[] =
    {
#if wxLUA_USE_wxPropertGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID
        { "wxPG_LABEL", wxPG_LABEL, NULL },
#endif // wxLUA_USE_wxPropertGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID


        { 0, 0 },
    };
    count = sizeof(stringList)/sizeof(wxLuaBindString) - 1;
    return stringList;
}

// ---------------------------------------------------------------------------
// wxLuaGetObjectList_wxpropgrid() is called to register object and pointer bindings
// ---------------------------------------------------------------------------

wxLuaBindObject* wxLuaGetObjectList_wxpropgrid(size_t &count)
{
    static wxLuaBindObject objectList[] =
    {

        { 0, 0, 0, 0 },
    };
    count = sizeof(objectList)/sizeof(wxLuaBindObject) - 1;
    return objectList;
}

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_wxpropgrid() is called to register global functions
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// wxLuaGetFunctionList_wxpropgrid() is called to register global functions
// ---------------------------------------------------------------------------

wxLuaBindMethod* wxLuaGetFunctionList_wxpropgrid(size_t &count)
{
    static wxLuaBindMethod functionList[] =
    {

        { 0, 0, 0, 0 }, 
    };
    count = sizeof(functionList)/sizeof(wxLuaBindMethod) - 1;
    return functionList;
}



// ---------------------------------------------------------------------------
// wxLuaGetClassList_wxpropgrid() is called to register classes
// ---------------------------------------------------------------------------


// ---------------------------------------------------------------------------
// Lua Tag Method Values and Tables for each Class
// ---------------------------------------------------------------------------




wxLuaBindClass* wxLuaGetClassList_wxpropgrid(size_t &count)
{
    static wxLuaBindClass classList[] =
    {

        { 0, 0, 0, 0, 0, 0, 0 }, 
    };
    count = sizeof(classList)/sizeof(wxLuaBindClass) - 1;

    return classList;
}

// ---------------------------------------------------------------------------
// wxLuaBinding_wxpropgrid() - the binding class
// ---------------------------------------------------------------------------

IMPLEMENT_DYNAMIC_CLASS(wxLuaBinding_wxpropgrid, wxLuaBinding)

wxLuaBinding_wxpropgrid::wxLuaBinding_wxpropgrid() : wxLuaBinding()
{
    m_bindingName   = wxT("wxpropgrid");
    m_nameSpace     = wxT("wx");
    m_classArray    = wxLuaGetClassList_wxpropgrid(m_classCount);
    m_numberArray   = wxLuaGetDefineList_wxpropgrid(m_numberCount);
    m_stringArray   = wxLuaGetStringList_wxpropgrid(m_stringCount);
    m_eventArray    = wxLuaGetEventList_wxpropgrid(m_eventCount);
    m_objectArray   = wxLuaGetObjectList_wxpropgrid(m_objectCount);
    m_functionArray = wxLuaGetFunctionList_wxpropgrid(m_functionCount);
    InitBinding();
}



// ---------------------------------------------------------------------------

wxLuaBinding* wxLuaBinding_wxpropgrid_init()
{
    static wxLuaBinding_wxpropgrid m_binding;

    if (wxLuaBinding::GetBindingArray().Index(&m_binding) == wxNOT_FOUND)
        wxLuaBinding::GetBindingArray().Add(&m_binding);

    return &m_binding;
}


