// ---------------------------------------------------------------------------
// wxpropgrid.h - headers and wxLua types for wxLua binding
//
// This file was generated by genwxbind.lua 
// Any changes made to this file will be lost when the file is regenerated
// ---------------------------------------------------------------------------

#ifndef __HOOK_WXLUA_wxpropgrid_H__
#define __HOOK_WXLUA_wxpropgrid_H__

#include "wxbind/include/wxbinddefs.h"
#include "wxluasetup.h"
#include "wxbind/include/wxcore_bind.h"

#include "wxlua/wxlstate.h"
#include "wxlua/wxlbind.h"

// ---------------------------------------------------------------------------
// Check if the version of binding generator used to create this is older than
//   the current version of the bindings.
//   See 'bindings/genwxbind.lua' and 'modules/wxlua/wxldefs.h'
#if WXLUA_BINDING_VERSION > 41
#   error "The WXLUA_BINDING_VERSION in the bindings is too old, regenerate bindings."
#endif //WXLUA_BINDING_VERSION > 41
// ---------------------------------------------------------------------------

// binding class
class WXDLLIMPEXP_BINDWXPROPGRID wxLuaBinding_wxpropgrid : public wxLuaBinding
{
public:
    wxLuaBinding_wxpropgrid();


private:
    DECLARE_DYNAMIC_CLASS(wxLuaBinding_wxpropgrid)
};


// initialize wxLuaBinding_wxpropgrid for all wxLuaStates
extern WXDLLIMPEXP_BINDWXPROPGRID wxLuaBinding* wxLuaBinding_wxpropgrid_init();

// ---------------------------------------------------------------------------
// Includes
// ---------------------------------------------------------------------------

#if wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID
    #include "wx/propgrid/advprops.h"
    #include "wx/propgrid/editors.h"
    #include "wx/propgrid/manager.h"
    #include "wx/propgrid/property.h"
    #include "wx/propgrid/propgrid.h"
    #include "wx/propgrid/propgriddefs.h"
    #include "wx/propgrid/propgridiface.h"
    #include "wx/propgrid/propgridpagestate.h"
    #include "wx/propgrid/props.h"
#endif // wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID

// ---------------------------------------------------------------------------
// Lua Tag Method Values and Tables for each Class
// ---------------------------------------------------------------------------

#if wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxBoolProperty;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxFloatProperty;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxIntProperty;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxNumericProperty;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxNumericPropertyValidator;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxPGAttributeStorage;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxPGPropArgCls;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxPGProperty;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxPGValidationInfo;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxPropertyGrid;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxPropertyGridEvent;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxPropertyGridInterface;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxStringProperty;
    extern WXDLLIMPEXP_DATA_BINDWXPROPGRID(int) wxluatype_wxUIntProperty;
#endif // wxLUA_USE_wxPropertyGrid && wxCHECK_VERSION(2,9,0) && wxUSE_PROPGRID



#endif // __HOOK_WXLUA_wxpropgrid_H__

