on:
  - pull_request
  - push

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        wx-version:
          - 3.0.5.1
          - 3.2.11
          # - 3.3.3

        lua-version:
          - system
          - 5.1
          - 5.2

        build-using:
          - make
          - cmake

      fail-fast: false

    name: "Build using ${{ case(matrix.build-using == 'make', 'GNU Make', 'CMake') }} on Linux, wxWidgets ${{ matrix.wx-version }}, ${{ case(matrix.lua-version == 'system', 'system Lua', format('Lua {0}', matrix.lua-version)) }}"
    steps:
      - name: Restore cached wxWidgets
        id: cache-wxwidgets-restore
        uses: actions/cache/restore@v6
        with:
          path: |
            /tmp/wxWidgets
          key: ${{ runner.os }}-${{ matrix.wx-version }}-1

      - name: Build wxWidgets ${{ matrix.wx-version }}
        if: steps.cache-wxwidgets-restore.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install -y \
              gettext \
              libcurl4-openssl-dev \
              libexpat1-dev \
              libgl-dev \
              libglu1-mesa-dev \
              libgstreamer-plugins-bad1.0-dev \
              libgtk-3-dev \
              libjpeg-dev \
              liblzma-dev \
              libnotify-dev \
              libpng-dev \
              libsm-dev \
              libtiff-dev \
              libwebkit2gtk-4.1-dev \
              libxt-dev \
              zlib1g-dev

          cd /tmp/
          wget https://github.com/wxWidgets/wxWidgets/releases/download/v${{ matrix.wx-version }}/wxWidgets-${{ matrix.wx-version }}.tar.bz2
          tar -xf wxWidgets-${{ matrix.wx-version }}.tar.bz2

          cd wxWidgets-${{ matrix.wx-version }}/
          ./configure --prefix /tmp/wxWidgets/
          make -j$(nproc)
          make install

      - name: Store wxWidgets for future builds
        id: cache-wxwidgets-save
        uses: actions/cache/save@v6
        if: steps.cache-wxwidgets-restore.outputs.cache-hit != 'true'
        with:
          path: |
            /tmp/wxWidgets
          key: ${{ steps.cache-wxwidgets-restore.outputs.cache-primary-key }}

      - uses: actions/checkout@v6

      - name: Build wxLua using GNU Make
        if: matrix.build-using == 'make'
        run: |
          sudo apt-get install -y \
              libgl-dev \
              libgstreamer-plugins-bad1.0-0 \
              libnotify4 \
              libreadline-dev \
              libjavascriptcoregtk-4.1-0 \
              libwebkit2gtk-4.1-0

          # wxWidgets 3.0 doesn't seem to support the version of webkit2gtk
          # used in modern Ubuntu, so we disable the webview bindings.
          if [ "${{ matrix.wx-version }}" = "3.0.5.1" ]
          then
              export WXLUA_ENABLE_BINDINGS="wxadv wxaui wxgl wxhtml wxmedia wxnet wxpropgrid wxrichtext wxstc wxxml wxxrc"
          fi

          if [ "${{ matrix.lua-version }}" = "system" ]
          then
              sudo apt-get install -y lua5.4 liblua5.4-dev
          fi

          export PATH="/tmp/wxWidgets/bin/:$PATH"
          make -C wxLua/                   BUILD_LUA="${{ case(matrix.lua-version == 'system', '', matrix.lua-version) }}"
          make -C wxLua/apps/wxlua/        BUILD_LUA="${{ case(matrix.lua-version == 'system', '', matrix.lua-version) }}"
          make -C wxLua/apps/wxluacan/     BUILD_LUA="${{ case(matrix.lua-version == 'system', '', matrix.lua-version) }}"
          make -C wxLua/apps/wxluafreeze/  BUILD_LUA="${{ case(matrix.lua-version == 'system', '', matrix.lua-version) }}"

      - name: Build wxLua using CMake
        if: matrix.build-using == 'cmake'
        run: |
          sudo apt-get install -y \
              libgl-dev \
              libgstreamer-plugins-bad1.0-0 \
              libnotify4 \
              libreadline-dev \
              libjavascriptcoregtk-4.1-0 \
              libwebkit2gtk-4.1-0

          if [ "${{ matrix.lua-version }}" = "system" ]
          then
              sudo apt-get install -y lua5.4 liblua5.4-dev
          fi

          mkdir wxLua-build/
          cd wxLua-build/

          cmake \
              -DwxWidgets_CONFIG_EXECUTABLE="/tmp/wxWidgets/bin/wx-config" \
              -DwxLua_LUA_LIBRARY_USE_BUILTIN=${{ case(matrix.lua-version == 'system', 'FALSE', 'TRUE') }} \
              -DwxLua_LUA_LIBRARY_VERSION=${{ case(matrix.lua-version == 'system', '5.4', matrix.lua-version) }} \
              ../wxLua/

          cmake --build . -j$(nproc)
